# Generated by Django 3.1.3 on 2020-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivemedicalrecords',
            name='deployment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
