# Generated by Django 3.1.3 on 2020-11-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_hivemedicalrecords_deployment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivemedicalrecords',
            name='medicine_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
