# Generated by Django 3.1.3 on 2020-11-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_hivemedicalrecords_medicine_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivemedical',
            name='medicine_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
