# Generated by Django 3.1.3 on 2020-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_hivemedicalrecords_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivemedicalrecords',
            name='apiaryID',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
