# Generated by Django 3.1.3 on 2020-12-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_hivemedicalrecords_apiaryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hivemedicalrecords',
            old_name='apiaryID',
            new_name='apiary_name',
        ),
    ]
