# Generated by Django 3.1.3 on 2021-01-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_auto_20210111_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivemedical',
            name='medicine_exp_date',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
