# Generated by Django 3.1.3 on 2021-01-21 16:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_auto_20210112_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivemedicalrecords',
            name='user',
            field=models.CharField(default=1, max_length=50, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
