# Generated by Django 3.1.1 on 2020-09-18 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apiry_details',
            new_name='Apiary_details',
        ),
    ]
