# Generated by Django 3.1.3 on 2021-01-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0002_apiary_details_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiary_details',
            name='phone_number',
        ),
    ]
