# Generated by Django 3.1.1 on 2020-09-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0004_auto_20200918_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiary_details',
            name='user',
        ),
    ]
