# Generated by Django 3.1.1 on 2020-09-23 11:12

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hive_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User)),
                ('hive_name', models.CharField(max_length=50)),
                ('apiary_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiary.apiary_details')),
            ],
            options={
                'verbose_name_plural': 'Hive Details',
            },
        ),
    ]
