# Generated by Django 3.1.3 on 2020-11-05 14:36

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hive_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User)),
                ('hive_name', models.CharField(max_length=50)),
                ('hive_type', models.CharField(choices=[('National', 'National'), ('Commercial', 'Commercial'), ('6 Frame Poly NUC', '6 Frame Poly NUC'), ('6 Frame Wooden NUC', '6 Frame Wooden NUC')], default='Unknown', max_length=50)),
                ('hive_new_apiary', models.CharField(blank=True, max_length=50, null=True)),
                ('hive_old_apiary', models.CharField(blank=True, max_length=50, null=True)),
                ('hive_move_date', models.DateField(blank=True, null=True)),
                ('apiary_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='apiary.apiary_details')),
            ],
            options={
                'verbose_name_plural': 'Hive Details',
            },
        ),
        migrations.CreateModel(
            name='hiveDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_and_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('queen', models.BooleanField(default=False)),
                ('queenColour', models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Not Marked', 'Not Marked')], default='Not Marked', max_length=50)),
                ('qc', models.BooleanField(default=False)),
                ('qcnum', models.IntegerField(blank=True, null=True)),
                ('eggs', models.BooleanField(default=False)),
                ('supers', models.BooleanField(default=False)),
                ('supersnum', models.IntegerField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('beekeepername', models.CharField(blank=True, max_length=30, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('hivenumber', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hives.hive_details')),
            ],
            options={
                'verbose_name_plural': 'Hive Documents',
            },
        ),
    ]
