# Generated by Django 3.1.3 on 2020-11-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hivedocuments',
            name='time_and_date',
        ),
        migrations.AddField(
            model_name='hivedocuments',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
