# Generated by Django 3.1.1 on 2020-09-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive_details',
            name='apiary_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
