# Generated by Django 3.1.1 on 2020-10-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0001_initial'),
        ('hives', '0002_auto_20200923_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive_details',
            name='apiary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiary.apiary_details'),
        ),
    ]
