# Generated by Django 3.1.3 on 2020-11-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0003_auto_20201109_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivedocuments',
            name='lave',
            field=models.BooleanField(default=False),
        ),
    ]
