# Generated by Django 3.1.3 on 2020-11-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0004_hivedocuments_lave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hivedocuments',
            old_name='lave',
            new_name='brood',
        ),
        migrations.RemoveField(
            model_name='hivedocuments',
            name='supers',
        ),
        migrations.AddField(
            model_name='hivedocuments',
            name='temperment',
            field=models.CharField(choices=[('Select', 'Select'), ('5 Calm', '5 Calm'), ('4', '4'), ('3', '3'), ('2', '2'), ('1 Evil', '1 Evil')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='hivedocuments',
            name='supersnum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
