# Generated by Django 3.1.3 on 2020-11-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0005_auto_20201109_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive_details',
            name='hive_type',
            field=models.CharField(choices=[('National', 'BS National'), ('14x12 National', '14x12 National'), ('Commercial', 'BS Commercial'), ('6 Frame Poly NUC', '6 Frame Poly NUC'), ('6 Frame Wooden NUC', '6 Frame Wooden NUC'), ('WBC', 'WBC'), ('CDB', 'CDB'), ('Langstroth', 'Langstroth'), ('Smith', 'Smith'), ('Top Bar', 'Top Bar'), ('Skep', 'Skep'), ('Dadant', 'Dadant'), ('Flow', 'Flow'), ('Warré', 'Warré'), ('Rose', 'Rose'), ('Dartington Long Deep', 'Dartington Long Deep'), ('Beehaus', 'Beehaus'), ('Long Box Hive', 'Long Box')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='hivedocuments',
            name='temperment',
            field=models.CharField(choices=[('5 Calm', '5 Calm'), ('4', '4'), ('3', '3'), ('2', '2'), ('1 Evil', '1 Evil')], default='5 Calm', max_length=20),
        ),
    ]
