# Generated by Django 3.1.3 on 2020-11-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0006_auto_20201109_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedocuments',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hivedocuments',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
