# Generated by Django 3.1.1 on 2020-10-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0007_auto_20201027_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive_details',
            name='hive_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
