# Generated by Django 3.1.3 on 2020-11-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0007_auto_20201130_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedocuments',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='hivedocuments',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
