# Generated by Django 3.1.1 on 2020-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0008_hive_details_hive_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive_details',
            name='hive_type',
            field=models.CharField(choices=[('National', 'National'), ('Commercial', 'Commercial'), ('6 Frame Poly NUC', '6 Frame Poly NUC'), ('6 Frame Wooden NUC', '6 Frame Wooden NUC')], default='Unknown', max_length=50),
        ),
    ]
