# Generated by Django 3.1.3 on 2021-01-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0003_remove_apiary_details_phone_number'),
        ('hives', '0009_auto_20201201_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive_details',
            name='apiary_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiary.apiary_details'),
        ),
    ]
