# Generated by Django 3.1.1 on 2020-10-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0010_hivedocs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hiveDocs',
            new_name='hiveDocuments',
        ),
    ]
