# Generated by Django 3.1.3 on 2021-01-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0010_auto_20210120_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedocuments',
            name='hivenumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hives.hive_details'),
        ),
    ]
