# Generated by Django 3.1.3 on 2021-02-21 12:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0011_auto_20210120_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivedocuments',
            name='user',
            field=models.CharField(default=1, max_length=50, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
