# Generated by Django 3.1.1 on 2020-10-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0012_auto_20201029_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivedocuments',
            name='queenColour',
            field=models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
    ]
