# Generated by Django 3.1.3 on 2021-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0012_hivedocuments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedocuments',
            name='brood',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hivedocuments',
            name='eggs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hivedocuments',
            name='qcnum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
