# Generated by Django 3.1.1 on 2020-10-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0013_hivedocuments_queencolour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedocuments',
            name='hive',
            field=models.CharField(max_length=30),
        ),
    ]
