# Generated by Django 3.1.3 on 2021-03-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0013_auto_20210331_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hivedocuments',
            name='qc',
        ),
    ]
