# Generated by Django 3.1.3 on 2021-03-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0014_remove_hivedocuments_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivedocuments',
            name='edit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
