# Generated by Django 3.1.1 on 2020-10-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0014_auto_20201029_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hivedocuments',
            old_name='hive',
            new_name='hivenumber',
        ),
    ]
