# Generated by Django 3.1.1 on 2020-10-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0015_auto_20201029_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedocuments',
            name='hivenumber',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hives.hive_details'),
        ),
    ]
