# Generated by Django 3.1.1 on 2020-10-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0016_auto_20201029_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedocuments',
            name='queenColour',
            field=models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Not Marked', 'Not Marked')], default='Not Marked', max_length=50),
        ),
    ]
