# Generated by Django 3.1.3 on 2021-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0016_remove_hivedocuments_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivedocuments',
            name='food',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
