# Generated by Django 3.1.3 on 2021-04-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0017_hivedocuments_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive_details',
            name='hive_merge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hive_details',
            name='hive_old_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
