# Generated by Django 3.1.1 on 2020-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0017_auto_20201030_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivedocuments',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='hivedocuments',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
