# Generated by Django 3.1.3 on 2021-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0018_auto_20210410_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive_details',
            name='old_hive_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
