# Generated by Django 3.1.3 on 2020-11-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0018_auto_20201102_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive_details',
            name='hive_new_apiary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hive_details',
            name='hive_old_apiary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
