# Generated by Django 3.1.3 on 2021-04-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0019_hive_details_old_hive_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hive_details',
            name='hive_merge_date',
        ),
    ]
