# Generated by Django 3.1.3 on 2020-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0019_auto_20201104_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive_details',
            name='hive_move_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
