# Generated by Django 3.1.3 on 2021-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0020_remove_hive_details_hive_merge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivedocuments',
            name='merged_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hivedocuments',
            name='merged_with',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
