# Generated by Django 3.1.3 on 2020-11-05 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0021_hivemedical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hivemedical',
            options={'verbose_name_plural': 'Hive Medical Medicine'},
        ),
        migrations.RemoveField(
            model_name='hivemedical',
            name='apiary_id',
        ),
        migrations.RemoveField(
            model_name='hivemedical',
            name='hive_name',
        ),
        migrations.RemoveField(
            model_name='hivemedical',
            name='hivenumber',
        ),
        migrations.RemoveField(
            model_name='hivemedical',
            name='medicine_admin_time_and_date',
        ),
        migrations.RemoveField(
            model_name='hivemedical',
            name='medicine_disposal',
        ),
        migrations.RemoveField(
            model_name='hivemedical',
            name='medicine_disposal_date',
        ),
        migrations.RemoveField(
            model_name='hivemedical',
            name='medicine_duration',
        ),
        migrations.RemoveField(
            model_name='hivemedical',
            name='medicine_qty_used',
        ),
        migrations.RemoveField(
            model_name='hivemedical',
            name='medicine_withdrawal',
        ),
        migrations.CreateModel(
            name='hiveMedicalRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive_name', models.CharField(max_length=50)),
                ('medicine_name', models.CharField(max_length=80)),
                ('medicine_admin_time_and_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('medicine_duration', models.CharField(max_length=20)),
                ('medicine_withdrawal', models.CharField(blank=True, max_length=50, null=True)),
                ('medicine_qty_used', models.CharField(max_length=20)),
                ('medicine_disposal', models.CharField(blank=True, max_length=150, null=True)),
                ('medicine_disposal_date', models.CharField(blank=True, max_length=20, null=True)),
                ('hivenumber', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hives.hive_details')),
            ],
            options={
                'verbose_name_plural': 'Hive Medical Records',
            },
        ),
    ]
