# Generated by Django 3.1.3 on 2020-11-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0022_auto_20201105_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hiveMedical',
        ),
        migrations.DeleteModel(
            name='hiveMedicalRecords',
        ),
    ]
