# Generated by Django 3.1.3 on 2021-04-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0024_auto_20210411_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive_details',
            name='been_merged',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hive_details',
            name='hive_type',
            field=models.CharField(choices=[('National', 'BS National'), ('National Polly', 'BS National Polly'), ('14x12 National', '14x12 National'), ('14x12 National Polly', '14x12 National Polly'), ('Commercial', 'BS Commercial'), ('Commercial Polly', 'BS Commercial Polly'), ('6 Frame Poly NUC', '6 Frame Poly NUC'), ('6 Frame Wooden NUC', '6 Frame Wooden NUC'), ('Apidea', 'Apidea'), ('WBC', 'WBC'), ('CDB', 'CDB'), ('Langstroth', 'Langstroth'), ('Langstroth Polly', 'Langstroth Polly'), ('Smith', 'Smith'), ('Top Bar', 'Top Bar'), ('Skep', 'Skep'), ('Dadant', 'Dadant'), ('Flow', 'Flow'), ('Warré', 'Warré'), ('Rose', 'Rose'), ('Dartington Long Deep', 'Dartington Long Deep'), ('Beehaus', 'Beehaus'), ('Long Box Hive', 'Long Box')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='hivedocuments',
            name='merged_with',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
